apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: transitwatch
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api
        image: ghcr.io/tues-2026-pbl-11-klas/transitwatch-api:0000000
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: transitwatch-secrets
              key: DATABASE_URL
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: transitwatch-secrets
              key: SUPABASE_URL
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: transitwatch-secrets
              key: SUPABASE_JWT_SECRET
        - name: PORT
          value: "3000"
        - name: CORS_ORIGIN
          value: "http://localhost"
