apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: transitwatch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: web
          image: ghcr.io/tues-2026-pbl-11-klas/transitwatch-web:latest
          ports:
            - containerPort: 80
